In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import calendar
import datetime

In [2]:
df=pd.read_csv(r"C:\Users\LENOVO\Downloads\1. Weather Data.csv")
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [3]:
#provides basic information about the dataframe:rows, columns, types(if automatically detected)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [4]:
# shows the first n rows in data(by default, n=5)
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [5]:
#find out different weather conditions available
df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [6]:
#find weather records with counts
df['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Snow,Haze                                     5
Freezing Rain,Fog                             4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Freezing Rain,Haze                            2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Moderate Rain,Fog                             1
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Name: count, dtype: int64

In [7]:
#find weather record clear with counts
df[(df.Weather=='Clear')].count()

Date/Time           1326
Temp_C              1326
Dew Point Temp_C    1326
Rel Hum_%           1326
Wind Speed_km/h     1326
Visibility_km       1326
Press_kPa           1326
Weather             1326
dtype: int64

In [8]:
len(df[df.Weather=='Clear'])

1326

In [9]:
#find all the wind speed values recorded in the dataset
df['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

In [10]:
df['Wind Speed_km/h'].value_counts()

Wind Speed_km/h
9     830
11    791
13    735
15    719
7     677
17    666
19    616
6     609
20    496
4     474
22    439
24    374
0     309
26    242
28    205
30    161
32    139
33     85
35     53
37     45
39     24
41     22
44     14
43     13
48     13
46     11
52      7
57      5
50      4
2       2
70      1
83      1
63      1
54      1
Name: count, dtype: int64

In [11]:
df['Wind Speed_km/h'].value_counts()[7]

np.int64(677)

In [12]:
len(df[df['Wind Speed_km/h']==7])

677

In [13]:
df[(df['Wind Speed_km/h']==7)].count()

Date/Time           677
Temp_C              677
Dew Point Temp_C    677
Rel Hum_%           677
Wind Speed_km/h     677
Visibility_km       677
Press_kPa           677
Weather             677
dtype: int64

In [14]:
# get weather and temp columns from dataset
df[['Weather','Temp_C']].head()

                Weather  Temp_C
0                   Fog    -1.8
1                   Fog    -1.8
2  Freezing Drizzle,Fog    -1.8
3  Freezing Drizzle,Fog    -1.5
4                   Fog    -1.5

In [15]:
#get first 20 rows from dataset
df[:20] # or df[0:20] or df.head(20)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,1/1/2012 7:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,1/1/2012 8:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,1/1/2012 9:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,1/1/2012 10:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,1/1/2012 11:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,1/1/2012 12:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,1/1/2012 13:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,1/1/2012 14:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,1/1/2012 15:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,1/1/2012 16:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,1/1/2012 17:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,1/1/2012 18:00,3.8,1.0,82,15,12.9,99.74,Rain
19,1/1/2012 19:00,3.1,1.3,88,15,12.9,99.68,Rain

In [16]:
# what were the first 5 pressure values recorded on jan 6
df['Date/Time']=pd.to_datetime(df['Date/Time'])
df.set_index('Date/Time',inplace=True)
df.loc['2012-01-06','Press_kPa'].head()

Date/Time
2012-01-06 00:00:00    100.81
2012-01-06 01:00:00    100.81
2012-01-06 02:00:00    100.84
2012-01-06 03:00:00    100.76
2012-01-06 04:00:00    100.70
Name: Press_kPa, dtype: float64

In [17]:
#find all instances when wind speed was above 30 and visibility 25
df[(df['Wind Speed_km/h']>30)& (df['Visibility_km']==25)]

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
Date/Time,,,,,,,
2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
2012-01-02 04:00:00,2.9,-2.3,69,32,25.0,99.26,Mostly Cloudy
...,...,...,...,...,...,...,...
2012-12-16 07:00:00,-9.8,-14.9,66,32,25.0,101.89,Cloudy
2012-12-21 18:00:00,1.4,0.3,92,46,25.0,97.56,Rain
2012-12-23 01:00:00,-7.9,-11.8,74,32,25.0,100.27,Snow Showers
2012-12-26 19:00:00,-9.6,-13.1,76,39,25.0,102.03,Cloudy
2012-12-26 22:00:00,-9.7,-12.8,78,37,25.0,101.70,Cloudy

In [18]:
# whih were thw top 10 hottest temp values and their counts
df['Temp_C'].value_counts().sort_values(ascending=False).head(10)

Temp_C
16.6    65
1.1     58
0.8     47
1.5     45
19.3    44
21.1    43
2.6     43
0.4     41
1.3     40
14.6    39
Name: count, dtype: int64

In [19]:
new_df=df['Temp_C'].value_counts().sort_values(ascending=False)
new_df[:10]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15172\701926445.py:2: FutureWarning: The behavior of obj[i:j] with a float-dtype index is deprecated. In a future version, this will be treated as positional instead of label-based. For label-based slicing, use obj.loc[i:j] instead
  new_df[:10]

Temp_C
 16.6    65
 1.1     58
 0.8     47
 1.5     45
 19.3    44
         ..
-8.8     17
 24.0    17
 3.6     17
 4.2     17
 10.0    17
Name: count, Length: 267, dtype: int64

In [20]:
#what is the means temp recorder by month
#one solution
mean_temperature={}

for month in range(1,13):
    mean_temperature[month]=df.loc[df.index.month==month,'Temp_C'].mean()
pd.Series(mean_temperature)

1     -7.371505
2     -4.225000
3      3.121237
4      7.009306
5     16.237769
6     20.134028
7     22.790054
8     22.279301
9     16.484444
10    10.954973
11     0.931389
12    -3.306317
dtype: float64

In [22]:
#or using pivot 
mean_temperature_df=df.pivot_table(values='Temp_C', index=df.index.month,aggfunc='mean')
mean_temperature_df

              Temp_C
Date/Time
1          -7.371505
2          -4.225000
3           3.121237
4           7.009306
5          16.237769
6          20.134028
7          22.790054
8          22.279301
9          16.484444
10         10.954973
11          0.931389
12         -3.306317

In [27]:
#or using groupby
mean_temperature_df=df.groupby(df.index.month).mean(numeric_only=True).reset_index()
mean_temperature_df['Temp_C']

0     -7.371505
1     -4.225000
2      3.121237
3      7.009306
4     16.237769
5     20.134028
6     22.790054
7     22.279301
8     16.484444
9     10.954973
10     0.931389
11    -3.306317
Name: Temp_C, dtype: float64

In [29]:
#extract month name from date and store it in new column named as month
df['Month']=df.index.month
df['Month']=df['Month'].apply(lambda x:calendar.month_name[x])
df.head()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather,Month
Date/Time,,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,January
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,January
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",January
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",January
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,January

In [41]:
#get the list of the months in whichh it rained with thunderstorm
def checklist(x):
    weather_list=['rain','thunderstorms']
    count=0
    x = str(x).lower()
    for substring in weather_list:
        if substring in x:
            count += 1
    if(count==2):
        return True
    else:
        return False
    
print ("2) get the list of the months in whichh it rained with thunderstorm\n" )
rained=df['Weather'].apply(checklist)
month_list=df[rained]['Month'].unique()
print(month_list)

2) get the list of the months in whichh it rained with thunderstorm

['May' 'June' 'July' 'August' 'September']